services:
  db:
    image: postgres:16
    container_name: gecko-db
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    networks:
      - gecko
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - gecko_db:/var/lib/postgresql/data
  riverui:
    image: ghcr.io/riverqueue/riverui:master
    container_name: riverui
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PGDATABASE=$POSTGRES_DB
      - PGUSER=$POSTGRES_USER
      - PGPASSWORD=$POSTGRES_PASSWORD
      - PGHOST=db
      - PGPORT=$POSTGRES_PORT
    networks:
      - gecko
volumes:
  gecko_db:

networks:
  gecko:

