name: Dagger
on:
  push:
    tags:
      - 'v*'
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILD_SUMMARY: true
  REPO: github.com/danielmichaels/doublestag

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: dagger/dagger-for-github@main
        with:
          version: '0.16.1'
          verb: call
          args: lint --src .
          module: ${{ env.REPO }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

