name: Dagger
on:
  push:
    tags:
      - 'v*'
    branches: [main]
  pull_request:
    branches: ['*']
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_BUILD_SUMMARY: true
  DAGGER_VERSION: '0.16.1'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: lint
        uses: dagger/dagger-for-github@main
        with:
          version: ${{ env.DAGGER_VERSION }}
          verb: call
          args: lint --src .
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: lint
        uses: dagger/dagger-for-github@main
        with:
          version: ${{ env.DAGGER_VERSION }}
          verb: call
          args: test --src .
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
